### PR TITLE
Add pan tool

### PR DESCRIPTION
**Pull request by Schweini07**
@luiq54 the second canvas is now dragable.

I also have to learn Git better. I needed one hour for finally putting this up and 1 minute working on it in Godot.

### CODE REVIEW

**Comment by luiq54** [comment]
Looks great!

**Review by OverloadedOrama — CHANGES_REQUESTED** [review]
So, functionality-wise it's very good! It will be a useful tool to have and it works well. However, I am mostly worried about the name of the tool, and its icon. A "move" tool usually refers to a tool that moves the pixels of the image (see #313) and not just the canvas. I think if we renamed it to "Pan" it would be a much better name. A hand icon, like this from Godot
image

also fits better for this purpose. I'd recommend using an icon like that for the Pan tool, and we can keep the one you made for a move tool that moves parts of the image.

If you could make these two changes, and if you agree of course, then I think it's ready to get merged. If you have issues making a hand icon, we could ask @Erevoid to handle that.


(Also, it's best if you avoided including files to the commit that don't have any relevant changes, like Main.tscn)

**Comment by Schweini07** [comment]
Thanks for the feedback!
Regarding Main.tscn, I had a lot of problems with Git, but maybe I am able to get it right this time.

**Comment by Schweini07** [comment]
I did the renaming, but I don't think I will get a good hand icon done.
I would have nothing against @Erevoid  making those.
Should I already push, with the old icons, or wait?

**Comment by OverloadedOrama** [comment]
> I did the renaming, but I don't think I will get a good hand icon done.
> I would have nothing against @Erevoid making those.
> Should I already push, with the old icons, or wait?

Go ahead. You can push the changes and we can merge the PR now, and change the icon later.

**Comment by Schweini07** [comment]
Done!

**Review by OverloadedOrama — APPROVED** [review]
Great, thank you!

**Pull request merged**
