### PR TITLE
Improve Cpu Usage while in Idle

### PR DESCRIPTION
**Pull request by Schweini07**
Cpu Usage is now 1% while in Idle.
Needs some testing for usability tough, set for v0.8.3/0.9.

### CODE REVIEW

**Comment by OverloadedOrama** [comment]
This is great! I tried it and the CPU usage when idle is indeed very noticeable. I'm a bit worried about the user experience though. The FPS is set to 1 when the mouse exits the window, which may confuse the users, especially when an animation is already playing. Perhaps it would be better if the behavior was changed to set the FPS to 1 when the window loses focus instead, and/or set this behavior toggleable in the Preferences.

**Comment by Schweini07** [comment]
I though about that. I also think that would be better, I'll update soon.

**Comment by Schweini07** [comment]
Done!

**Review by OverloadedOrama — APPROVED** [review]
Looks good, thank you!

**Comment by KripC2160** [comment]
Really cool to see these features be added! I knew sometimes I would forget to close the program and my computer fans would be going crazy while I was doing other stuff in the background.

**Pull request merged**
