### PR TITLE
Add a Delete Button and a Copy Button for frames

### PR DESCRIPTION
**Pull request by Schweini07**
You can now click on the delete button and you do not have to open the popup menu

### CODE REVIEW

**Comment by novhack** [comment]
You can also delete with a middle mouse click on a frame.

**Comment by Schweini07** [comment]
Quick question then: Are there other shortcuts for the actions in the popupmenu? Because copying frames for instance, is also a bit cumbersome. Thanks!

**Comment by Schweini07** [comment]
Now there's also a copy button so that the PR is more useful

**Comment by Schweini07** [comment]
Just noticed, I forgot the tooltips, please wait a bit

**Comment by Schweini07** [comment]
Should work now, I hope I didn't conflict with the HSVDialog PR

**Comment by Schweini07** [comment]
I did conflict, but should be resolved now

**Comment by OverloadedOrama** [comment]
Using the latest commit, I only see the remove button and its hint tooltip is the same as the add button. Did you put the copy button on the scene, or only as a file?
image

**Comment by Schweini07** [comment]
Should work now, I forgot the AnimationTimeline.tscn

**Comment by OverloadedOrama** [comment]
Looks good, I'll go ahead and merge. Thanks!

**Pull request merged**
