### PR TITLE
Allow greater values than 100 for ToSpinBox

### LINKED ISSUE #403: Frame Tag stuck at 100 frame
**Pixelorama version:**0.8.1

**OS/device including version:**linux mint 20

**Issue description:**frame tag can't tag more than 100 frame animation

**Steps to reproduce:** -

### PR DESCRIPTION
**Pull request by Schweini07**
Closes #403.

### CODE REVIEW

**Comment by OverloadedOrama** [comment]
Maybe this should also be done for "FromSpinBox", so users can set the starting frame of the tag to one higher than 100.

**Comment by Schweini07** [comment]
Weird, the pull request closed itself, could it because I changed the commit message?

Anyways "FromSpinBox" now also allows greater values.

**Comment by Schweini07** [comment]
Woops forgot to reopen.

**Review by OverloadedOrama — APPROVED** [review]
Thank you!

**Pull request merged**
