### PR TITLE
Upgrade/floodfill

### PR DESCRIPTION
**Pull request by MatteoPiovanelli-Laser**
As discussed in #639 , this is my attempt at implementing the floodfill routine in gdscript

### CODE REVIEW

**Comment by MatteoPiovanelli-Laser** [comment]
Of course last night I forgot to check formatting guidelines and such. I'll take care of that after work. Sorry for that.

**Comment by MatteoPiovanelli-Laser** [comment]
@OverloadedOrama sorry to ping you. I think with my updates this PR should be able to pass the checks in the automated workflows now, but it needs authorization for those to run.

**Comment by OverloadedOrama** [comment]
> @OverloadedOrama sorry to ping you. I think with my updates this PR should be able to pass the checks in the automated workflows now, but it needs authorization for those to run.

My bad, I thought I had to authorize it once. Done!

**Comment by MatteoPiovanelli-Laser** [comment]
I did more reformatting. Apparently I had been too zealous with going to new lines for function parameters, according to the parser.

**Comment by MatteoPiovanelli-Laser** [comment]
Further refactoring. The linter failed on a line that the parser had me change. I hope it's good for both now.

**Comment by MatteoPiovanelli-Laser** [comment]
I wish I could run the format/lint tasks on my machine, but there is an issue in gdtoolkit and their scripts error out on my pc.

**Comment by OverloadedOrama** [comment]
> Further refactoring. The linter failed on a line that the parser had me change. I hope it's good for both now.

I think the reason it fails is because of this bug https://github.com/Scony/godot-gdscript-toolkit/issues/148. Best thing we can do for now is to add `# gdlint: ignore=max-line-length` in the previous line.



> I wish I could run the format/lint tasks on my machine, but there is an issue in gdtoolkit and their scripts error out on my pc.

Yeah unfortunately if I remember correctly it's not working properly on Windows.

**Comment by MatteoPiovanelli-Laser** [comment]
The code finally passes all automated checks. Let me know any further improvements you require.

**Comment by OverloadedOrama** [comment]
For the most part it seems to be working well, but there's weird behavior when using flood fill with non-rectangular selections.
This is what happens when I use the bucket tool on an elliptical selection.
image

While this is the expected behavior.
image

For some reason, it seems to only be filling the areas with the same width. I have observed this behavior only with selections, if we draw an ellipse and use the bucket tool inside it, the result is what we expect.

**Comment by MatteoPiovanelli-Laser** [comment]
I'm checking now. The issue with the code in my PR is indeed on those lines. It's not correctly checking whether the segment above (or below) should be checked in cases where there is a selection area. Basically, it's testing above (or below) the left-most pixel of the segment.
I'm working on a fix.

**Comment by MatteoPiovanelli-Laser** [comment]
The quick fix would be

```
segment.todo_above = position.y > 0
segment.todo_below = position.y < project.size.y - 1
```

That seems to cover it all. I'm working on something more precise.

**Comment by MatteoPiovanelli-Laser** [comment]
I ended up going for that quick fix, with some comments explaining it, because it's just quicker than the alternatives I found.

**Review by OverloadedOrama — APPROVED** [review]
I've tested it and found no other issues. The performance increase is definitely there, so this seems to be good to merge. Thank you!

**Pull request merged**
