### PR TITLE
Replace old palette system with a new one

### PR DESCRIPTION
**Pull request by novhack**
I completely remade the palette system. Basically all features from #356 are implemented except undo/redo support.

This pull request breaks compatibility with old palettes. When I was redesigning the load/save system I decided to go with Resource format for palettes so the old JSON won't load anymore. Keeping legacy JSON related code seemed like a bad idea.

image
New dialogs:
image
image

### CODE REVIEW

**Comment by kleonc** [comment]
Issues (not sure if related to undo/redo being not implemented yet):

<details>
<summary> GUI is not being instantly updated when modyfying palettes loaded from the disk (not created at the current Pixelorama run). </summary>

#### Examples:
1. Drag and drop:
Godot_v3 2 3-stable_win64_SrjKZRXRIA
2.  Add / remove colors:
Bk05LKWNOK

</details>


<details>
<summary> Editing palette loaded from the disk (not created at the current Pixelorama run) duplicates the entry in the palettes dropdown. </summary>

kVpm5SAOHU

</details>

**Comment by novhack** [comment]
Thank you for testing. What operating system do you use? I see that the path for the palette is in res:// which doesn't happen to me - all imported palettes should be stored/copied to appdata.

**Comment by kleonc** [comment]
Windows 7. I was running [this version](https://github.com/novhack/Pixelorama/tree/6fc801c3eb19bdf7ba836d0fb9398f6588b4f3ce) in debug mode, right from the Godot.
<details><summary> All I have in appdata are: a backup, config file and some logs. </summary> 

```
C:\Users\MyUsername\AppData\Roaming\Godot\app_userdata\Pixelorama\backup-1609273475-0
C:\Users\MyUsername\AppData\Roaming\Godot\app_userdata\Pixelorama\cache.ini
C:\Users\MyUsername\AppData\Roaming\Godot\app_userdata\Pixelorama\logs
C:\Users\MyUsername\AppData\Roaming\Godot\app_userdata\Pixelorama\logs\godot.log
C:\Users\MyUsername\AppData\Roaming\Godot\app_userdata\Pixelorama\logs\godot_2021-01-31_13-04-56.log
C:\Users\MyUsername\AppData\Roaming\Godot\app_userdata\Pixelorama\logs\godot_2021-01-31_13-05-38.log
C:\Users\MyUsername\AppData\Roaming\Godot\app_userdata\Pixelorama\logs\godot_2021-01-31_13-09-35.log
C:\Users\MyUsername\AppData\Roaming\Godot\app_userdata\Pixelorama\logs\godot_2021-01-31_14-20-33.log
```
</details>

I've just downloaded current official version (`Pixelorama [Windows 64-bit].zip`) from [the site](https://orama-interactive.itch.io/pixelorama) and it has `pixelorama_data` directory right next to the `.exe` and that's where palettes are being added/edited. Same happens in your version: it's indeed modyfying contents of `./pixelorama_data/Palettes/`.

**Review by Erevoid — COMMENTED** [review]
Eyo!

I tested your PR, I really like the new palette system in general. I'd like to comment some details I figured out while playing with the settings:
1. When you put high values on width and height it can crash the program. For example I put 100 for both width and height, and Pixelorama froze for several seconds. When I tried to add a color, it crashed. Μaybe have a limitation as to how many colours can be added with relatively no problem in most devices?
2. You can have 0 as the value for width or height, if there is no specific reason for that, why not have a minimum value of 1?
3. When you select a colour from the palette and then you switch the colour from the colour picker (not the palette's colour), the palette colour remains selected. That's a bit confusing since you have a specific colour shown at the colour picker and a different one selected at the palette, so I suggest deselecting the palette colour when the user changes the colour of the colour picker.
4. When the user creates a new palette it's not clear enough that a name is required so that the Ok button can be pressed. That can be fixed by adding some red text indicating that the name is missing when the field is empty

**Comment by novhack** [comment]
At this point all the issues kleonc and Erevoid had should be resolved.

Palette size now has no impact on performance.
It's possible to scroll with a middle button in the palette panel.
There is now also an importer for "old" json palette format for backwards compatibility.

**Comment by novhack** [comment]
I added two small fixes based on luiq54's feedback on Discord.

**Comment by Erevoid** [comment]
Didn't find any new issues after the changes, it's looking good in my opinion!

**Review by OverloadedOrama — APPROVED** [review]
I think it looks good too. I've been testing it and it seems to be working well, so I'll go ahead and merge it now. Thank you!

**Pull request merged**
