### PR TITLE
Further speed up of bucket fill

### PR DESCRIPTION
**Pull request by MatteoPiovanelli-Laser**
By cutting down on some tests that were being repeated after a point had already been found to be one to be colored, I made the flood fill a bit faster again.

### CODE REVIEW

**Review by OverloadedOrama — APPROVED** [review]
I tried it and it seems to work great! I was under the impression that the only way the bucket fill would speed up like this would be using GDNative, and I am glad to be proven wrong. Thank you!

**Comment by Variable-ind** [comment]
@MatteoPiovanelli-Laser I found a bug, pixels enclosed as shown here don't get effected by flood fill even if you click on top of it

https://user-images.githubusercontent.com/77773850/166229362-07a35e21-e221-42f4-bc80-5340d9d87bd1.mp4

**Comment by MatteoPiovanelli-Laser** [comment]
I'm on the wrong machine to test this right now. Does the same issue happen regardless of whether you click to the right or to the left of the affected pixel? Looks to me I might have done a +2 where I needed to do a +1 or something like that where I'm computing where segments start. I'll see if I can check this later tonight.

**Comment by Variable-ind** [comment]
yes, also i narrowed it down to this pull here: https://github.com/Orama-Interactive/Pixelorama/pull/681

**Comment by Variable-ind** [comment]
i have narrowed it down further to line 305 of bucket.gd
is it safe to do `if segment.right_position >= segment.left_position:`
instead of `if segment.right_position > segment.left_position:`
cause that removes the bug

**Comment by MatteoPiovanelli-Laser** [comment]
Yes, that actually makes a lot of sense. The code from my PR causes only segments at least two pixels long to be colored

**Comment by MatteoPiovanelli-Laser** [comment]
@Variable-ind do you want to go ahead and do the PR with the fix or should I?

**Comment by Variable-ind** [comment]
i think you should do it :smiley:
it's just a single line change right?
`if segment.right_position = segment.left_position:` to `if segment.right_position >= segment.left_position:`
in that case we could ask @OverloadedOrama to commit it internally (in that case the pull wont be necessary)

**Comment by OverloadedOrama** [comment]
Fixed in 9e7dd1210b27aa83da0f955eaa73f0d61f44f17d

**Pull request merged**
