### PR TITLE
Shader Rotation fix

### PR DESCRIPTION
**Pull request by Variable-ind**
Tried to fix the bug caused by shader rotation mentioned in discord.
I hope i did everything right...

### CODE REVIEW

**Comment by AlphinAlbukhari** [comment]
Alright I've found the formula
`COLOR.rgb = mix(mix(original.rgb, rotated.rgb, rotated.a * border), rotated.rgb, selection)`

image

**Comment by AlphinAlbukhari** [comment]
Also it looks darker because when selection is enabled, it will blend the image (on GDScript), this is already blended by shader so blending them 2 times doubles the alpha. Could you add this please
`	if _project.has_selection and selection_checkbox.pressed and type_option_button.text != "Nearest neighbour (Shader)":`

**Comment by Variable-ind** [comment]
Done :+1:

**Comment by Variable-ind** [comment]
I also took the liberty to add the quick rotation buttons mentioned in https://github.com/Orama-Interactive/Pixelorama/issues/675#issue-1213379672

https://user-images.githubusercontent.com/77773850/166100506-2e5f9f9c-9554-4956-b341-5cb6e0d9a4ed.mp4

**Review by OverloadedOrama — APPROVED** [review]
It is best to keep [separate PRs for multiple changes](https://github.com/Orama-Interactive/Pixelorama/blob/master/CONTRIBUTING.md#contributing-pull-requests); the rotation buttons would have been better as another PR and this one strictly for the bug fix, but the changes look good so I'll go ahead and merge. Thanks!

**Pull request merged**
