### PR TITLE
Simple Discord RPC Support 

### PR DESCRIPTION
**Pull request by FrozenGamer1640**
Just a simple support to the Discord RPC using a Godot addon
( Please check the comments inside the src/Classes/DiscordRPC.gd file )

PS: sorry for the extra commit, I forgot to change the README.md

### CODE REVIEW

**Comment by OverloadedOrama** [comment]
I think such a feature would be best suited as an optional extension. I don't know if it's a good idea to include dll/so files in the base application, which also increase the size of several MBs, for a feature not many people will want to use.

**Comment by FrozenGamer1640** [comment]
I actually tried to code it as an extension, but I couldn't get the extension to contain the godot addon I used for it in a way that pixelorama could use. and (as I marked as "NOTE's" on the script comments) I couldn't use C# to code it manually.

**Comment by FrozenGamer1640** [comment]
Ok, my appologies for my lazyness, I didn't actually investigated enought, apparently Godot has native support to websockets and JSON format. I'm sorry for wasting your time, I'll close de PR.

**Comment by Variable-ind** [comment]
i'm making this extension, it'll be online soon :grin: https://github.com/Variable-Interactive/PixeloramaDiscordRPC/tree/master

**Pull request closed without merging**
